### ISSUE TITLE
Huffman code possible issue

### ISSUE THREAD

**Issue by twharmon** [Algorhythm-sxv/connect4-ai#3]
Should the `_huffman_code` function return `code >> 1` instead of `code << 1`? I think you've appended "0" 8 times (for 7x6) when only 6 are necessary.

**Comment by Algorhythm-sxv** [comment]
It's been a long time since I've looked at this project, but I think that it works either way, and the provided opening database now depends on that coding.

**Comment by twharmon** [comment]
I was using that for an 8 ply database, and only had space for 22 bits, so I had to change it.
